// components/Footer.tsx
export default function Footer() {
  return (
    <footer className="bg-[#0f0f0f] pt-20 pb-10 px-6 md:px-12 lg:px-16">

      {/* Tagline */}
      <div className="border-b border-white/10 pb-16 mb-16 text-center">
        <p
          className="font-playfair text-white font-normal"
          style={{
            fontSize: 'clamp(2rem, 4vw, 3.5rem)',
            fontStyle: 'italic',
            letterSpacing: '-0.02em',
          }}
        >
          Tecnologia. Territori. Futur.
        </p>
      </div>

      {/* Three columns */}
      <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-12">

        {/* Col 1 — logo + tagline */}
        <div>
          <div className="flex items-center gap-2.5">
            <span className="w-6 h-6 bg-white rounded-sm inline-block shrink-0" aria-hidden="true" />
            <span className="text-[15px] font-semibold tracking-tight text-white">
              Pirineu Tech
            </span>
          </div>
          <p className="text-sm text-[#555] mt-3 max-w-xs leading-[1.6]">
            El node tecnològic de l&apos;Alt Pirineu i Aran.
          </p>
        </div>

        {/* Col 2 — Organització */}
        <div>
          <p className="text-xs uppercase tracking-[0.15em] text-[#444] mb-4">
            Organització
          </p>
          {['Missió i Visió', "Línies d'actuació", 'Transparència'].map((link) => (
            <a
              key={link}
              href="#"
              className="text-sm text-[#666] hover:text-white transition-colors duration-150 mb-2 block"
            >
              {link}
            </a>
          ))}
        </div>

        {/* Col 3 — Contacte */}
        <div>
          <p className="text-xs uppercase tracking-[0.15em] text-[#444] mb-4">
            Contacte
          </p>
          <p className="text-sm text-[#666] mb-2">Plaça dels Oms, 1</p>
          <p className="text-sm text-[#666] mb-2">25700 La Seu d&apos;Urgell</p>
          <a
            href="mailto:info@pirineu.tech"
            className="text-sm text-[#666] hover:text-white transition-colors duration-150"
          >
            info@pirineu.tech
          </a>
        </div>

      </div>

      {/* Bottom bar */}
      <div className="max-w-7xl mx-auto border-t border-white/10 mt-16 pt-8 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <p className="text-xs text-[#444]">
          © 2026 Pirineu Tech · Tots els drets reservats
        </p>
        <p className="text-xs text-[#444] hover:text-white transition-colors duration-150 cursor-pointer">
          Desenvolupat per Milato Studio
        </p>
      </div>

    </footer>
  )
}

// src/lib/components/ui/Footer.svelte
<script lang="ts">
  const currentYear = new Date().getFullYear();
</script>

<footer class="bg-dark-900 border-t border-white/10 py-16">
  <div class="max-w-7xl mx-auto px-6">
    <div class="grid grid-cols-1 md:grid-cols-[2fr_1fr_1fr_1fr] gap-10">
      <!-- Brand -->
      <div>
        <p class="font-display font-bold text-xl text-text-light mb-3">Pirineu Tech</p>
        <p class="font-body text-sm text-text-light/50 leading-relaxed max-w-xs">
          Associació privada sense ànim de lucre per a la transformació
          tecnològica de l'Alt Pirineu i Aran.
        </p>
      </div>

      <!-- Projectes -->
      <div>
        <p class="font-body font-semibold text-xs uppercase tracking-widest text-text-light/40 mb-4">
          Projectes
        </p>
        <ul class="flex flex-col gap-3">
          <li><a href="#projectes" class="font-body text-sm text-text-light/60 hover:text-text-light transition-colors">Pyrenlab</a></li>
          <li><a href="#projectes" class="font-body text-sm text-text-light/60 hover:text-text-light transition-colors">Infraestructura digital</a></li>
        </ul>
      </div>

      <!-- Organització -->
      <div>
        <p class="font-body font-semibold text-xs uppercase tracking-widest text-text-light/40 mb-4">
          Organització
        </p>
        <ul class="flex flex-col gap-3">
          <li><a href="#el-projecte" class="font-body text-sm text-text-light/60 hover:text-text-light transition-colors">Qui som</a></li>
          <li><a href="#linies" class="font-body text-sm text-text-light/60 hover:text-text-light transition-colors">Línies estratègiques</a></li>
          <li><a href="#novetats" class="font-body text-sm text-text-light/60 hover:text-text-light transition-colors">Novetats</a></li>
        </ul>
      </div>

      <!-- Contacte -->
      <div>
        <p class="font-body font-semibold text-xs uppercase tracking-widest text-text-light/40 mb-4">
          Contacte
        </p>
        <ul class="flex flex-col gap-3">
          <li><a href="#adhesio" class="font-body text-sm text-text-light/60 hover:text-text-light transition-colors">Fes-te soci</a></li>
          <li><a href="mailto:hola@pirineutech.cat" class="font-body text-sm text-text-light/60 hover:text-text-light transition-colors">hola@pirineutech.cat</a></li>
        </ul>
      </div>
    </div>

    <!-- Bottom bar -->
    <div class="mt-14 pt-8 border-t border-white/10 flex flex-col md:flex-row items-center justify-between gap-4">
      <p class="font-body text-xs text-text-light/30">
        © {currentYear} Pirineu Tech. Tots els drets reservats.
      </p>
      <div class="flex gap-6">
        <a href="/avis-legal" class="font-body text-xs text-text-light/30 hover:text-text-light/60 transition-colors">Avís legal</a>
        <a href="/politica-privacitat" class="font-body text-xs text-text-light/30 hover:text-text-light/60 transition-colors">Política de privacitat</a>
      </div>
    </div>
  </div>
</footer>
